spring.application.name=e-support-hub-backend
server.port=${PORT:8080}
server.address=0.0.0.0
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/e_support_hub}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:e_support_hub}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:e_support_hub}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false